### ISSUE TITLE
java: 程序包com.codeborne.selenide不存在

### ISSUE THREAD

**Issue by luoqianze** [dima123493/AirlinesManagerTycoonHelper_Selenide#2]
![image](https://github.com/dima123493/AirlinesManagerTycoonHelper_Selenide/assets/47841929/b01ee875-c3c9-47ee-b36a-1a4ee7fb5ede)

**Comment by dima123493** [comment]
Hi, thank you for creating this issue! 
Seems like it can not find Selenide library. Try to open pom.xml file and Load Maven changes. If <artifactId>selenide</artifactId> is absent, add [Selenide dependency](https://mvnrepository.com/artifact/com.codeborne/selenide).
